### ISSUE TITLE
Do you have the intrinsic value of the camera generating the depth and RGB textures？

### ISSUE THREAD

**Issue by fp2162** [enric1994/cut-seg#1]
Hello, thank you for the open source dataset. I want to convert the depth map in the data set into a normal map for viewing, but I did not find the relevant camera intrinsic parameters in the project. If so, can you provide it? Thank you so much

**Comment by enric1994** [comment]
Hello! I used the default camera in Blender, but I have no idea of such parameters. Fortunately, I found [this](https://mcarletti.github.io/articles/blenderintrinsicparams/) script from @mcarletti that computes it. Here's the output:
```
>>> get_calibration_matrix_K_from_blender(mode='simple')
array([[  1.05000000e+03,   0.00000000e+00,   4.80000000e+02],
       [  0.00000000e+00,   1.05000000e+03,   2.70000000e+02],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]], dtype=float32)
```

Hope it helps,

Enric
